name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deploy/deployment.yaml
          kubectl apply -f deploy/services.yaml
          kubectl apply -f deploy/ingress.yaml
          kubectl rollout restart deployment bootcamp-frontend-deployment
    